### PR TITLE
Update gameoflife.ino

### PR DESCRIPTION
**Pull request by ioprojecton**

### CODE REVIEW

**Comment by TechNerd1** [comment]
Getting an error, unterminated argument list invoking macro "crNum"

**Comment by TechNerd1** [comment]
Same error
"Arduino: 1.8.5 (Mac OS X), Board: "Arduino/Genuino Zero (Programming Port)"

gameoflife2:120: error: unterminated argument list invoking macro "crNum"
exit status 1
unterminated argument list invoking macro "crNum"

**Comment by ioprojecton** [comment]
problem solved forgot closing bracket when calling macro

**Review by TechNerd1 — APPROVED** [review]

**Comment by ioprojecton** [comment]
Will it fit on uno?

**Comment by TechNerd1** [comment]
yes

**Comment by ioprojecton** [comment]
How if its using 115% ram on uno?

**Comment by TechNerd1** [comment]
I mean I haven't tried it but I think it should work. Not 100% though

**Comment by ioprojecton** [comment]
What about encodig each pixel in bit? 
You will need 32 longs. 
Long h[32]
Esch long is 32bit so you will get 32x32 bits.
Compiled size code will be 10 times smaller.
I cant work on it am very busy with other projects.

**Pull request merged**
