### PR TITLE
Update gameoflife.ino

### PR DESCRIPTION
**Pull request by ioprojecton**

### CODE REVIEW

**Review by TechNerd1 — CHANGES_REQUESTED** [review]
It doesn't work properly. I looked around the code but haven't found the issue. It loops a few times then stops.

**Comment by ioprojecton** [comment]
I rechecked the code it must work. Original version works without faults?

**Comment by TechNerd1** [comment]
I checked your code and it's a lot more clean but I can't find anywhere
where the issue is.

**Comment by ioprojecton** [comment]
Try with changing animation speed to const byte

**Comment by TechNerd1** [comment]
Tried it but gives an error, looking for the issue still.

**Comment by ioprojecton** [comment]
Dont have same hardware to test. Check the counter value when its stopping and go from there.

**Comment by TechNerd1** [comment]
Found the issue, it's bugging out where the two 2D arrays copy.

**Comment by TechNerd1** [comment]
so line 83 and 111.

**Comment by ioprojecton** [comment]
My bad should be col++=col

**Review by TechNerd1 — APPROVED** [review]

**Comment by TechNerd1** [comment]
lol youre good and thx btw, im use to java and this is very similar.

**Comment by ioprojecton** [comment]
Always welcome

**Pull request merged**
